"""add uuid transaction owner

Revision ID: 46f7d62e9c0b
Revises: 55954cd31e9a
Create Date: 2026-09-26 23:20:32.875413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46f7d62e9c0b'
down_revision: Union[str, Sequence[str], None] = '55954cd31e9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('owner_user_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_transactions_owner_user_id'), 'transactions', ['owner_user_id'], unique=False)
    op.create_foreign_key(None, 'transactions', 'users', ['owner_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_owner_user_id'), table_name='transactions')
    op.drop_column('transactions', 'owner_user_id')
    # ### end Alembic commands ###
